version: "3"

services:
  db-postgres:
    image: postgres:15.3-alpine
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_NAME}
    ports:
      - 5441:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  node:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
